services:
  bank-marketing-analysis:
    image: shizhezhang/bank-marketing-analysis:6b67f6b
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64