services:
  jupyter-lab:
    image: shizhezhang/bank-marketing-analysis:eabea47
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64

  terminal:
    image: shizhezhang/bank-marketing-analysis:eabea47
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64